# -*- coding: utf-8 -*-
"""BookRecommendationSystem.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13OCBQXgM3tERpnvKhXOh0Ia2wy6kssTH
"""

public class BookRecommendationSystem {
    private List<User> users;
    private List<Book> books;

    public BookRecommendationSystem() {
        this.users = new ArrayList<>();
        this.books = new ArrayList<>();
    }

    public void addUser(User user) {
        users.add(user);
    }

    public List<Book> recommendBooks(User user) {
        // 추천 알고리즘 구현
        return new ArrayList<>();
    }
}