# -*- coding: utf-8 -*-
"""Movie.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cCHMcL50lChtqrhDEyHTX6mB4tmR6FsV
"""

import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;

class Movie {
    String title;
    String genre;
    String description;

    Movie(String title, String genre, String description) {
        this.title = title;
        this.genre = genre;
        this.description = description;
    }
}

public class MovieRecommendationSystem {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        List<Movie> movies = new ArrayList<>();

        // 영화 데이터 추가
        movies.add(new Movie("인셉션", "SF", "꿈 속의 꿈을 다룬 스릴러."));
        movies.add(new Movie("타이타닉", "로맨스", "사랑과 비극의 이야기."));
        movies.add(new Movie("어벤져스", "액션", "슈퍼히어로들이 모여 악당과 싸우는 이야기."));
        movies.add(new Movie("겨울왕국", "애니메이션", "자매의 사랑과 모험을 그린 이야기."));

        System.out.println("영화 추천 시스템에 오신 것을 환영합니다! 장르나 키워드를 입력하세요.");

        while (true) {
            String userInput = scanner.nextLine();

            if (userInput.equalsIgnoreCase("종료")) {
                System.out.println("시스템을 종료합니다. 좋은 하루 되세요!");
                break;
            }

            boolean found = false;
            for (Movie movie : movies) {
                if (movie.genre.equalsIgnoreCase(userInput) || movie.title.contains(userInput)) {
                    System.out.println("추천 영화: " + movie.title + " - " + movie.description);
                    found = true;
                }
            }

            if (!found) {
                System.out.println("죄송합니다. 해당 장르나 키워드에 맞는 영화가 없습니다.");
            }
        }

        scanner.close();
    }
}