# -*- coding: utf-8 -*-
"""Quiz.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iliumJB7LkDm_aXlknG4V-DBPIxT9Lc_
"""

import java.util.Random;
import java.util.Scanner;

public class QuizBot {

    public static void main(String[] args) {
        // 초기 메시지 출력
        System.out.println("AI 퀴즈봇에 오신 것을 환영합니다! 퀴즈를 시작합니다. '종료'라고 입력하여 종료하세요.");

        // 퀴즈 데이터
        String[][] quizData = {
            {"1+1은 무엇일까요?", "2"},
            {"한국의 수도는 어디일까요?", "서울"},
            {"자바(Java)는 어떤 프로그래밍 언어인가요? (힌트: 객체지향 or 절차지향)", "객체지향"},
            {"지구는 태양 주위를 몇 년에 한 바퀴 돌까요?", "1년"}
        };

        // Scanner로 사용자 입력 받기
        Scanner scanner = new Scanner(System.in);
        Random random = new Random();

        while (true) {
            // 랜덤으로 퀴즈 선택
            int randomIndex = random.nextInt(quizData.length);
            String question = quizData[randomIndex][0];
            String answer = quizData[randomIndex][1];

            // 퀴즈 출력
            System.out.println("퀴즈봇: " + question);
            System.out.print("사용자: ");
            String input = scanner.nextLine().trim();

            // '종료' 입력 시 종료
            if (input.equalsIgnoreCase("종료")) {
                System.out.println("퀴즈봇: 이용해 주셔서 감사합니다! 다음에 또 만나요.");
                break;
            }

            // 정답 확인
            if (input.equalsIgnoreCase(answer)) {
                System.out.println("퀴즈봇: 정답입니다! 잘하셨어요!");
            } else {
                System.out.println("퀴즈봇: 틀렸어요. 정답은 '" + answer + "'입니다.");
            }
        }

        scanner.close();
    }
}